### ISSUE TITLE
V-Sekai crash on start on RADV, Ubuntu 22.04.2 LTS (Jammy Jellyfish)

### ISSUE THREAD

**Issue by 20kdc** [V-Sekai/v-sekai-game#115]
### Issue description

I'm aware this is presumably in very early development, and am simply sending this as it seems to be the kind of error that could cause other weirdness.

On start, V-Sekai crashes with the following output:
[v_sekai_linuxbsd.txt](https://github.com/V-Sekai/v-sekai-game/files/11276318/v_sekai_linuxbsd.txt)

Some notes:
* `--xr-mode off` does not avoid this problem
* I have not so far run into equivalent issues with normal builds of Godot 4.0.3, but then I'm not sure if I have or have not poked at exported Godot 4.0.x projects either.
* llvmpipe (selected via `--gpu-index`) does avoid the crash but is not particularly performant.
* Passing `--gpu-validation` appears to freeze with `Validation Information: [ UNASSIGNED-cache-file-error ] Object`. Moving `~/.local/share/godot/shader_cache` had no effect on the result.
* Passing `--rendering-driver opengl3` causes an entirely different crash. [opengl3crash.txt](https://github.com/V-Sekai/v-sekai-game/files/11276407/opengl3crash.txt)

The following error (seen in the opengl3 crash) always occurs on any successful startup (via i.e. llvmpipe), but is not fatal in-and-of-itself:
```
Installing service: Uro
ERROR: self can't be used because instance is null (not passed)
   at: execute (core/math/expression.cpp:1507)
ERROR: Expression execute error: self can't be used because instance is null (not passed)
   at: push_error (core/variant/variant_utility.cpp:902)
```

Additional OS information:
[glxinfo.txt](https://github.com/V-Sekai/v-sekai-game/files/11276316/glxinfo.txt)
[vulkaninfo.txt](https://github.com/V-Sekai/v-sekai-game/files/11276396/vulkaninfo.txt)

### Steps to reproduce

1. Be running a system similar to mine?
2. Download Linux nightly from https://saracenone.itch.io/groups-4x (`Version groups-4.0.groups-4.0.0.3fb42cea.505.962-2023-04-11T11:43:09+00:00`)
3. Extract
4. Run from a terminal (to see the resulting error)

### Minimal reproduction project (For SDK or engine issues)

*Not applicable.*

### Using a released version?

Yes

### What OS? Any other relevant information? (V-Sekai version, Godot revision, System information)

Ubuntu 22.04.2 LTS (Jammy Jellyfish) -- no headset -- Engine version: Godot Engine v4.0.3.groups-4.0.0.505.custom_build (3fb42ceab3d9364a65412e6b5a27b0853674fce2)

**Comment by fire** [comment]
I spent some time using an amd graphics card to try and recreate the issue.

**Comment by 20kdc** [comment]
So `groups-4.0.groups-4.0.0.f3956ccc.556.1127-2023-06-28T20:37:47+00:00` does not act differently. If that was the only development I wouldn't be sending this comment, but I decided to actually look in GDB at what happens when it freezes.

The answer is... odd.

```
(gdb) bt
#0  0x00007f15b7cc0f9f in ?? () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#1  0x00007f15b7cc1a57 in ?? () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#2  0x00007f15b7cc31e4 in _Unwind_RaiseException () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#3  0x00007f15b02ae50b in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007f15b02a5315 in std::__throw_bad_cast() () from /lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007f15b033d4be in std::ostream& std::ostream::_M_insert<unsigned long>(unsigned long) () from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007f15ac467683 in ?? () from /lib/x86_64-linux-gnu/libVkLayer_khronos_validation.so
#7  0x00007f15ac468672 in ?? () from /lib/x86_64-linux-gnu/libVkLayer_khronos_validation.so
#8  0x00007f15ac46acb6 in ?? () from /lib/x86_64-linux-gnu/libVkLayer_khronos_validation.so
#9  0x00007f15ac461d84 in ?? () from /lib/x86_64-linux-gnu/libVkLayer_khronos_validation.so
#10 0x00007f15ac467c32 in ?? () from /lib/x86_64-linux-gnu/libVkLayer_khronos_validation.so
#11 0x00007f15ac4562af in ?? () from /lib/x86_64-linux-gnu/libVkLayer_khronos_validation.so
#12 0x00007f15ac3c0814 in ?? () from /lib/x86_64-linux-gnu/libVkLayer_khronos_validation.so
#13 0x00007f15ac124cea in ?? () from /lib/x86_64-linux-gnu/libVkLayer_khronos_validation.so
#14 0x00007f15abe54c8e in ?? () from /lib/x86_64-linux-gnu/libVkLayer_khronos_validation.so
#15 0x00000000015f20bf in ?? ()
#16 0x0000000003b6b7b0 in ?? ()
#17 0x0000000003b6c08b in ?? ()
#18 0x0000000003c9de68 in ?? ()
#19 0x0000000003b5981a in ?? ()
#20 0x000000000045aeeb in ?? ()
#21 0x0000000003a8caa4 in ?? ()
#22 0x0000000000498f2d in ?? ()
#23 0x0000000000492dff in ?? ()
#24 0x000000000042851e in ?? ()
#25 0x00007f15c0229d90 in __libc_start_call_main (main=main@entry=0x428490, argc=argc@entry=2, argv=argv@entry=0x7fffa1c24178) at ../sysdeps/nptl/libc_start_call_main.h:58
#26 0x00007f15c0229e40 in __libc_start_main_impl (main=0x428490, argc=2, argv=0x7fffa1c24178, init=<optimised out>, fini=<optimised out>, rtld_fini=<optimised out>, stack_end=0x7fffa1c24168)
    at ../csu/libc-start.c:392
#27 0x00000000004283ce in ?? ()
```
It seems to spend forever somewhere in the validation layer repeatedly throwing exceptions?
I think I may need to compile with debug symbols to get some answers...

**Comment by 20kdc** [comment]
So, annoyingly, my own personal engine build off of... well, the commit ID is in the logs; crashes in a completely different manner.
This is run against the same PCK as the above, not run off of an attempt to build the game or anything.
Here be the logs.
[stderr.log](https://github.com/V-Sekai/v-sekai-game/files/11910852/stderr.log)
[stdout.log](https://github.com/V-Sekai/v-sekai-game/files/11910853/stdout.log)

**Comment by fire** [comment]
Not sure where to start.

**Comment by fire** [comment]
Hearing reports that it is now working. Comments soon.

**Comment by bagleman** [comment]
Issue non-reproducable on 0.1alpha6
Kubuntu 23.04 - 7900xtx
Kernel Version - 6.2.0-33 generic
Graphics Platform X11

**Comment by 20kdc** [comment]
Can confirm that 0.1alpha6 starts on my system. It warns me about missing assemblies, but what's there works.

Closing. Thanks!
