### ISSUE TITLE
Add open-source chat servers

### ISSUE THREAD

**Issue by GrimPixel** [V-Sekai/v-sekai-game#122]
### Describe the proposed feature and how it helps to overcome a problem or limitation

XMPP and Matrix.org are open chat protocols. Their users don't necessarily use Discord.

**Comment by fire** [comment]
We have a matrix space. It is not widely advertised.

**Comment by fire** [comment]
Sorry for the delay. Here's the link

https://matrix.to/#/#v-sekai:matrix.org
