### ISSUE TITLE
Be able to grab network entities

### ISSUE THREAD

**Issue by fire** [V-Sekai/v-sekai-game#15]
### Describe the proposed feature and how it helps to overcome a problem or limitation

Like grab a beach ball.

### Other information about your context or usecase.

Be able to grab and pass to each other.

**Comment by fire** [comment]
Merged with https://github.com/V-Sekai/v-sekai-game/issues/14

**Comment by lyuma** [comment]
I'm not sure why this got closed prematurely, but lasso should now be working in main 2a37345. it currently requires that you tilt the joystick slightly to the right before gripping to avoid interfering with movement, but we'll try and work out input mappings to make this less ugly.
