### ISSUE TITLE
A grey screen is shown when connecting multiple clients to a server

### ISSUE THREAD

**Issue by lyuma** [V-Sekai/v-sekai-game#18]
### Issue description

Non-server clients show a grey screen and don't load fully.
```
Attempted to register duplicate network instance_id
```
is printed on the server. it may also be printed on the clients. Unsure if this is related.
Both fire and lyuma reproduced.

Happens both in sky celebration (with entities) and also on the apartment of ants with the tv 

### Steps to reproduce

1. Host a game with a server.
2. The server should work
3. Then connect a client to Direct IP 127.0.0.1
4. The client will show grey screen
5. The server should see a empty client floating at spawn.

### Using a released version?

No

### What OS? Any other relevant information? (V-Sekai version, Godot revision, System information)

Windows

**Comment by fire** [comment]
I didn't see this happen. What are the conditions to recreate it?

**Comment by lyuma** [comment]
It was caused by some GDScript errors that were fixed the beginning of last week I think.
