### ISSUE TITLE
Desktop window is black in VR

### ISSUE THREAD

**Issue by lyuma** [V-Sekai/v-sekai-game#20]
### Issue description

The menu works fine, but after hosting or joining a map, the desktop window turns black.

### Steps to reproduce

1. Start the game
2. Host a game.
3. Window is black
4. Hit esc, and menu shows up again.

### Using a released version?

Both

### What OS? Any other relevant information? (V-Sekai version, Godot revision, System information)

Windows 10, Nvidia

**Comment by fire** [comment]
Still occurs in Feburary 2023.

**Comment by fire** [comment]
Fixed after https://github.com/V-Sekai/v-sekai-game/commit/6221bf469685bb780d91c649b189c3fb5f139502
