### ISSUE TITLE
Uploaded maps are pink or with messed up lighting

### ISSUE THREAD

**Issue by lyuma** [V-Sekai/v-sekai-game#21]
### Issue description

Most uploaded content looks pink shaded. It appears that all textures are missing. I am not sure yet if the missing textures are pink or white (weird lighting)

### Steps to reproduce

1. Upload sky_celebration.tscn to a new pipeline id.
2. The scene will appear like this in game.
3. You can see "sky celebration beta3" already uploaded to see this.

### Using a released version?

Both

### What OS? Any other relevant information? (V-Sekai version, Godot revision, System information)

Windows 10, Nvidia

**Comment by fire** [comment]
Related to the camera attribute not being said. I can't find the source of quote.

**Comment by fire** [comment]
https://github.com/godotengine/godot/issues/68052

**Comment by fire** [comment]
Map downloads are not pink anymore.

https://user-images.githubusercontent.com/32321/205993579-e39097e1-e325-4dd4-8c83-5f8ecdf8f566.mp4
