### ISSUE TITLE
VR doesn't work

### ISSUE THREAD

**Issue by EnthWyrr** [V-Sekai/v-sekai-game#228]
### Issue description

VR doesn't seem to work as of opening this issue.
While Oculus and SteamVR (in my case) do open while OpenXR is enabled in the project's settings, the functionality just doesn't seem to be there.
Even if I open my respective VR software before running, it will just run on Flat Mode instead.

### Steps to reproduce

Run V-Sekai with a VR headset connected, before or after booting up its respective software.

(closest - https://github.com/V-Sekai/v-sekai-game/commit/328c01ec1b52de34572fba0d1af35e26bafbebeb)

### Using a released version?

No

### What OS? Any other relevant information? (V-Sekai version, Godot revision, System information)

Windows 10, Oculus Rift

**Comment by fire** [comment]
I'm checking this as soon as I can.

**Comment by fire** [comment]
I am testing an alternative fix, and a map upload fix.

**Comment by EnthWyrr** [comment]
I tried to run it in VR just now and it works!
The controllers don't work well for some reason, but I'll just open a new issue for that.
