### ISSUE TITLE
Raycast rays from the menu remain visible in game

### ISSUE THREAD

**Issue by marc-weber1** [V-Sekai/v-sekai-game#246]
### Issue description

Ray objects extending from controller are visible in game after menu closes

### Steps to reproduce

Load the game normally, and log into any server

### Using a released version?

dc4754b263d67b51b355ff4a80a96b7cbd1bc2fc

### What OS? Any other relevant information? (V-Sekai version, Godot revision, System information)

Windows 10, SteamVR, Virtual Desktop, Quest 1

**Comment by fire** [comment]
Closed as of https://github.com/V-Sekai/v-sekai-game/pull/226
