### ISSUE TITLE
When loading into a server without selecting an avatar, the default is invisible

### ISSUE THREAD

**Issue by marc-weber1** [V-Sekai/v-sekai-game#247]
### Issue description

See title

### Steps to reproduce

Load the game and join a server

### Using a released version?

dc4754b263d67b51b355ff4a80a96b7cbd1bc2fc

### What OS? Any other relevant information? (V-Sekai version, Godot revision, System information)

Windows 10, SteamVR, Virtual Desktop, Quest 1

**Comment by fire** [comment]
As part of https://github.com/V-Sekai/v-sekai-game/commit/16c32fb8b2ffcb8049e97fb3e4656c627b4caf21 we default to an existing public avatar.
