### ISSUE TITLE
Desktop viewport is not rendered

### ISSUE THREAD

**Issue by EnthWyrr** [V-Sekai/v-sekai-game#341]
### Issue description

When playing on flat (desktop) mode, the desktop viewport is not rendered, with the screen being completely pink instead.
![imagen](https://github.com/V-Sekai/v-sekai-game/assets/51394825/b876f7e5-0bbd-467b-a174-506aa3f0a580)
This renders the game unplayable.

### Steps to reproduce

- Open the game.
- Go to a map. Start or join a server.

### Using a released version?

No

### What OS? Any other relevant information? (V-Sekai version, Godot revision, System information)

Windows 10 (but it also happens under Linux Mint), godot-groups-4.2 (v4.2.beta.custom_build [dd18872ba]). NVIDIA GeForce GTX 1060 with Forward+ (Vulkan) renderer.

**Comment by fire** [comment]
Previously, I unmerged a pr but I decided against it because it's an unnecessary divergence - https://github.com/V-Sekai/godot/commit/d917975a67b9bcb887a1141b38a4c64f9f7a31b4

**Comment by fire** [comment]
Fixed by https://github.com/V-Sekai/v-sekai-game/pull/348.

**Comment by fire** [comment]
See https://github.com/V-Sekai/v-sekai-game/issues/351 also
