### ISSUE TITLE
Avatars imported before beta have broken LODs.

### ISSUE THREAD

**Issue by lyuma** [V-Sekai/v-sekai-game#7]
### Issue description

All existing binary models have heavy LODing

![Screenshot showing cursed heavily decimated Xbot](https://cdn.discordapp.com/attachments/598003845657788438/1032821203804626994/Screenshot_Thu_Oct_20_17-07-17_2022.png)

### Steps to reproduce

1. Settings -> Player -> Avatar -> choose any existing public model.
2. Host Game -> Host -> look at arms or legs.

**Comment by fire** [comment]
Resolved by reverting to before float=64.
